adjust_header_search:
  type: string
  default: '120px'
  description:
    en: Adjust header search field position (relative distance from logo)
custom_homepage:
  type: bool
  default: false
  description:
    en: Custom layout for your homepage. Requires the Featured Lists component.
show_categories:
  type: bool
  default: true
  description:
    en: Show categories on the interface
show_tags:
  type: bool
  default: true
  description:
    en: Show tags on the interface
sidebar_show_more:
  type: bool
  default: false
  description:
    en: Show the More menu on the sidebar
